CORE
main.py
--function fail

^VERIFICATION FAILED$
