THOROUGH
main.py
--ir
^VERIFICATION FAILED$
